version: '2'
services:
  peer-base:
    image: hyperledger/fabric-peer
    environment:
      - CORE_PEER_ADDRESSAUTODETECT=true
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=e2e_default
      #  if set to any value, CORE_LOGGING_LEVEL overrides all the others
      #- CORE_LOGGING_LEVEL=DEBUG
      #- CORE_LOGGING_PEER=DEBUG
      #- CORE_LOGGING_NODE=DEBUG
      #- CORE_LOGGING_NETWORK=DEBUG
      #- CORE_LOGGING_VERSION=DEBUG
      #- CORE_LOGGING_PROTOUTILS=DEBUG
      #- CORE_LOGGING_ERROR=DEBUG
      #- CORE_LOGGING_MSP=DEBUG
      - CORE_NEXT=true
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_ENDORSER_ENABLED=true
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_PROFILE_ENABLED=true
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: peer node start --peer-defaultchain=false
